### ISSUE TITLE
Version 6.0.0 throwing errors in React Native

### ISSUE THREAD

**Issue by MyPalVikram** [iconoir-icons/iconoir#226]
I installed the latest version and started getting the error in the screenshot below. Downgrading one version resolves this issue.

## Prerequisites

* Version: 6.0.0
* Are you running from source/main:
* Are you using a released build:
* Operating system:
* Bits:

## Step to reproduce

Installing the latest version and running.

## Any message or error

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-08 at 19 23 15](https://user-images.githubusercontent.com/6226652/211236383-1bf61cc9-9f23-420c-ab11-20895fb0796c.png)

**Comment by sammarks** [comment]
We renamed a lot of the icons in version 6 (it was a major upgrade because renaming icons is a breaking change), so I imagine the error you're getting is because you're using the old name of an icon.

Check out [the changelog](https://iconoir.com/docs/changelog) for a list of icons we renamed.

If you provide a code sample of the icon you're trying to import that's causing the error I could show you the new name of the icon (I can only see a partial name in the error message).

**Comment by kartorias1** [comment]
Hi, I'm having the same issue after updating the iconoir-react-native package from 6.5.0 to 7.0.3. I have checked all of the icon names and all of them are correct compared to the names on the official documentation so this might not be the problem.

**Comment by paescuj** [comment]
> Hi, I'm having the same issue after updating the iconoir-react-native package from 6.5.0 to 7.0.3. I have checked all of the icon names and all of them are correct compared to the names on the official documentation so this might not be the problem.

Please create a new issue with all necessary information if this is still a problem for you. Thanks!
