### ISSUE TITLE
is there a way to provide a Categorize/Tag for these icons?

### ISSUE THREAD

**Issue by visualsitemaps** [iconoir-icons/iconoir#296]
since there are so many, we want to offer users a simple visual segmentation.

example:

**Arrows**
- icon 1, icon 2, etc 

**Transport**
- icon 1, icon 2

**System**
- icon 1, icon 2

*I know we can do this inside our apps..but asking if it can come pre-tagged.

**Comment by sammarks** [comment]
I would say providing those tags as part of the JS / Swift / etc packages is outside the scope of those packages (especially since the categories on offer can be opinionated depending on the type of product they're being listed in).

If it helps, you can find the full list of icons and the categories (as well as their search tags) that the website uses [here.](https://github.com/iconoir-icons/iconoir/blob/main/iconoir.com/icons.csv)
