### ISSUE TITLE
[Vue warn]: injection "Symbol()" not found.  when using with Vue and Typescript

### ISSUE THREAD

**Issue by a1eksb** [iconoir-icons/iconoir#399]
## Prerequisites
Using iconoir (@iconoir/vue: 7.3.0) with vue 3.4.15 and typescript 5.3.3 I get the warning "[Vue warn]: injection "Symbol()" not found." every time import and use a new icon.

Example usage: 
`import {Mail} from '@iconoir/vue'`

`<Mail width="1em" height="1em" stroke-width="1.5" />`

The icons render fine but it would be nice to not have these warnings int he console.

Thanks for providing a fantastic set of icons! :) 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/399">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/399/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/399/pledge.svg">
</picture>
</a>

**Comment by shroomlife** [comment]
`[Vue warn]: injection "Symbol()" not found.`

Same issue here with following packages:
```
@iconoir/vue 7.4.0
Nuxt 3.10.2
vue 3.4.19
```
Icons work but Warnings come up...

**Comment by SBLCoding** [comment]
I'm have the same issue when importing an icon using vue and typescript

**Comment by elvinaspredkelis** [comment]
Same issue here. Icons do work, but the application is polluted with these warnings

**Comment by KennLDN** [comment]
Apologies for the necro, is it just me or is this issue not resolved?
@iconoir/vue 7.10.1
vue 3.5.13

`main.ts:14 [Vue warn]: injection "Symbol()" not found. `

I get this warn no matter what way I implement

**Comment by elvinaspredkelis** [comment]
It's probably not yet released. Waiting on it as well

**Comment by fernandogiroto** [comment]
I've found a temporary solution.
In the plugin's node modules we have this: 

`export { default as IconoirProvider } from "./IconoirProvider.vue";`

So what I did was import provider like this:
`import { IconoirProvider, Home, Search, SimpleCart, User, LogOut, Menu } from '@iconoir/vue';`

If you are using typescript, put it this way:

` <IconoirProvider :iconProps="{}">
       <Search width="42" height="42" />
    </IconoirProvider>
`

O :iconProps="{}" it's not mandatory, but since I'm using Typescript it will give me an error alert because in the IconoirProvider interface it has these props:

```
import type { SVGAttributes } from 'vue-demi';
interface Props {
    iconProps: SVGAttributes;
}
```

The warning will no longer appear. It's temporary, because it's not ideal and it's easy to fix in future versions of the plugin.
